# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.wso2.apk.secretProviderClass.enabled }}
{{- if eq .Values.wso2.apk.secretProviderClass.provider "vault" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - secretName: {{ template "apk-helm.resource.prefix" . }}-secrets
      type: Opaque
      data:
        - objectName: ratelimiter_redis_credentials
          key: ratelimiter_redis_credentials
    - secretName: {{ template "apk-helm.resource.prefix" . }}-system-listener-tls
      type: Opaque
      data:
        - objectName: system-api-listener.secretName
          key: tls.secretName
        - objectName: system-api-listener.crt
          key: tls.crt
    - secretName: {{ template "apk-helm.resource.prefix" . }}-router-tls
      type: Opaque
      data:
        - objectName: router.secretName
          key: tls.secretName
        - objectName: router.crt
          key: tls.crt
  parameters:
    vaultAddress: {{ .Values.wso2.apk.secretProviderClass.vault.url }}
    roleName: {{ .Values.wso2.apk.secretProviderClass.vault.roleName }}
    objects: |
      - objectName: ratelimiter_redis_credentials
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterRedisCredentials.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterRedisCredentials.version | quote }}
      - objectName: adapter.secretName
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterKey.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterKey.version | quote }}
      - objectName: adapter.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterCert.version | quote }}
      - objectName: adapter-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterCaCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterCaCert.version | quote }}
      - objectName: enforcer.secretName
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerKey.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerKey.version | quote }}
      - objectName: enforcer.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerCert.version | quote }}
      - objectName: enforcer-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerCaCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerCaCert.version | quote }}
      - objectName: router.secretName
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.routerKey.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.routerKey.version | quote }}
      - objectName: router.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.routerCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.routerCert.version | quote }}
      - objectName: router-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.routerCaCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.routerCaCert.version | quote }}
      - objectName: ratelimiter.secretName
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterKey.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterKey.version | quote }}
      - objectName: ratelimiter.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterCert.version | quote }}
      - objectName: ratelimiter-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterCaCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterCaCert.version | quote }}
      - objectName: commoncontroller.secretName
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerKey.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerKey.version | quote }}
      - objectName: commoncontroller.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerCert.version | quote }}
      - objectName: commoncontroller-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerCaCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerCaCert.version | quote }}
      - objectName: system-api-listener.secretName
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.systemApiListenerKey.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.systemApiListenerKey.version | quote }}
      - objectName: system-api-listener.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.systemApiListenerCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.systemApiListenerCert.version | quote }}
      - objectName: enforcer-jwks.secretName
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksKey.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksKey.version | quote }}
      - objectName: enforcer-jwks.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksCert.version | quote }}
      - objectName: enforcer-jwks-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksCaCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksCaCert.version | quote }}
{{ if and .Values.wso2.apk.dp.gatewayRuntime.tracing .Values.wso2.apk.dp.gatewayRuntime.tracing.enabled .Values.wso2.apk.dp.gatewayRuntime.tracing.configProperties .Values.wso2.apk.dp.gatewayRuntime.tracing.configProperties.tls .Values.wso2.apk.dp.gatewayRuntime.tracing.configProperties.tls.enabled }}
      - objectName: tracing-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.tracingCaCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.tracingCaCert.version | quote }}
      - objectName: tracing.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.tracingCert.secretName | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.tracingCert.version | quote }}
{{- end }}
{{- end }}
{{- end }}
